---
repos:
  - repo: https://github.com/asottile/add-trailing-comma
    rev: v2.4.0
    hooks:
      - id: add-trailing-comma

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-toml
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: check-merge-conflict
      - id: end-of-file-fixer
      - id: check-added-large-files
      - id: check-byte-order-marker
      - id: check-case-conflict
      - id: check-docstring-first
      - id: check-json
      - id: check-symlinks
      - id: detect-private-key
      - id: check-ast
      - id: debug-statements

  - repo: https://github.com/pycqa/pydocstyle.git
    rev: 6.3.0
    hooks:
      - id: pydocstyle

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.0.0
    hooks:
      - id: mypy
        exclude: '^(docs|tasks|tests)|setup\.py'
        args: ["--ignore-missing-imports", "--explicit-package-bases"]
        additional_dependencies: [attrs~=19.3]

  - repo: https://github.com/psf/black
    rev: 23.1.0
    hooks:
      - id: black

  - repo: https://github.com/pycqa/flake8
    rev: "6.0.0"
    hooks:
      - id: flake8
        additional_dependencies: ["pep8-naming"]
        # Ignore all format-related checks as Black takes care of those.
        args:
          [
            "--ignore",
            "E2,W5,N818",
            "--select",
            "E,W,F,N",
            "--max-line-length=130",
          ]
